# Site settings
title: 
header-img: img/home-bg.png
email: meghan.gutshall@gmail.com
copyright_name: meg-gutshall
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: meg_gutshall
github_username:  meg-gutshall
learn_profile: meg-gutshall
email_username: meghan.gutshall@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
